-- This file generated by protoc-ddl.
-- Generated by MySQL Generator (v0.1)

SET foreign_key_checks=0;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`age` INTEGER NOT NULL DEFAULT 20,
	`name` VARCHAR(255) NOT NULL,
	`created_at` DATETIME NOT NULL,
	PRIMARY KEY(`id`)
) Engine=InnoDB;

DROP TABLE IF EXISTS `blog`;
CREATE TABLE `blog` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`user_id` INTEGER NOT NULL,
	`title` VARCHAR(100) NOT NULL,
	`body` TEXT NOT NULL,
	`category_id` INTEGER NOT NULL,
	`attach` LONGBLOB NOT NULL,
	`created_at` DATETIME NOT NULL,
	`updated_at` DATETIME NULL,
	UNIQUE `idx_user_id_and_id` (`user_id`,`id`),
	INDEX `idx_user_id_category_id` (`user_id`,`category_id`),
	PRIMARY KEY(`id`)
) Engine=InnoDB;

DROP TABLE IF EXISTS `comment`;
CREATE TABLE `comment` (
	`blog_id` BIGINT NOT NULL,
	`user_id` INTEGER NOT NULL,
	PRIMARY KEY(`blog_id`,`user_id`)
) Engine=InnoDB;

DROP TABLE IF EXISTS `like`;
CREATE TABLE `like` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INTEGER NOT NULL,
	`blog_id` BIGINT NOT NULL,
	PRIMARY KEY(`id`)
) Engine=InnoDB;

DROP TABLE IF EXISTS `post_image`;
CREATE TABLE `post_image` (
	`id` INTEGER NOT NULL,
	`url` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
) Engine=InnoDB;

SET foreign_key_checks=1;
