// Generated by protoc-ddl.
// protoc-gen-entity: v0.1
package sample

import (
	"time"
)

var _ = time.Time{}

type User struct {
	Id        int32
	Age       int32
	Name      string
	CreatedAt time.Time
}

type Blog struct {
	Id         int64
	UserId     int32
	Title      string
	Body       string
	CategoryId int32
	Attach     []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type CommentImage struct {
	CommentBlogId int64
	CommentUserId int32
	LikeId        uint64
}

type Comment struct {
	BlogId int64
	UserId int32
}

type Reply struct {
	Id            int32
	CommentBlogId int64
	CommentUserId int32
	Body          string
}

type Like struct {
	Id     uint64
	UserId int32
	BlogId int64
}

type PostImage struct {
	Id  int32
	Url string
}
