package main

import (
	"bytes"
	"os"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"

	"go.f110.dev/protoc-ddl/internal/generator"
	"go.f110.dev/protoc-ddl/internal/schema"
)

func main() {
	req, err := schema.ParseInput(os.Stdin)
	if err != nil {
		panic(err)
	}
	opt, tables := schema.ProcessDDL(req)

	var res pluginpb.CodeGeneratorResponse
	buf := new(bytes.Buffer)
	buf.WriteString("-- This file generated by protoc-ddl.\n")

	switch opt.Dialect {
	case "mysql":
		generator.MySQLGenerator{}.Generate(buf, tables)
	}

	res.File = append(res.File, &pluginpb.CodeGeneratorResponse_File{
		Name:    proto.String(opt.OutputFile),
		Content: proto.String(buf.String()),
	})

	output, err := proto.Marshal(&res)
	if err != nil {
		panic(err)
	}
	os.Stdout.Write(output)
}
